sigstore/protobuf-specs

.github/workflows/generate.yml
Makefile
README.md

- Updates Makefile to actually generate all required files (-f only includes the last entry)
- Update github check action to make sure we are checking all code
Signed-off-by: Appu Goundan <appu@google.com>

Update code gen verification

---

.github/workflows/gradle-wrapper-validation.yml
.github/workflows/java-build.yml

Signed-off-by: Appu Goundan <appu@google.com>
fixes #23

Put gradle wrapper validation in its own action

---

.github/workflows/python-build.yml
gen/pb-python/LICENSE
gen/pb-python/README.md
gen/pb-python/pyproject.toml

This should act as a smoketest for the generated Python that @tetsuo-cpp added with #25.

CI: python-build

---

.github/workflows/python-release.yml
gen/pb-python/Makefile
gen/pb-python/pyproject.toml

Per #22: this is a demonstration of how we can mostly automate our releases, in this case for Python.
cc @loosebazooka @znewman01

Automatic Python release workflow

---

.github/workflows/python-release.yml

Signed-off-by: Zachary Newman <zjn@chainguard.dev>
See #32

Fix Python release workflow (hopefully)

---

.github/workflows/python-release.yml

Fix Python release, take 2.

---

gen/pb-go/bundle/v1/sigstore_bundle.pb.go
gen/pb-go/common/v1/sigstore_common.pb.go
gen/pb-python/sigstore_protobuf_specs/dev/sigstore/bundle/v1/__init__.py
gen/pb-python/sigstore_protobuf_specs/dev/sigstore/common/v1/__init__.py
protos/sigstore_bundle.proto
protos/sigstore_common.proto

See #44.
Signed-off-by: William Woodruff <william@trailofbits.com>

gen, protos: update guidance on key IDs, fix a few typos

---

gen/pb-python/pyproject.toml

Signed-off-by: Fredrik Skogman <kommendorkapten@github.com>
Updated `pyproject.toml`
N/A
N/A

Update pyproject.toml to include the correct version

---

RELEASE.md

Signed-off-by: Fredrik Skogman <kommendorkapten@github.com>
Added `RELEASE.md` which describes the step for releasing new versions of the messages and language clients.
N/A
N/A
cc: @loosebazooka @woodruffw

Added a RELEASE.md

---

.github/ISSUE_TEMPLATE/release-checklist.md

Signed-off-by: Appu Goundan <appu@google.com>
Proposal for a simple release-checklist

Add release-checklist.md

---

java/README.md

Signed-off-by: Appu <appu@google.com>

Minor update to Java README.md

---

RELEASE.md

Update Golang release

---

RELEASE.md

Add Ruby release instructions, update version updates

---

CHANGELOG.md

Closes #91.
cc @kommendorkapten @haydentherapper

CHANGELOG: initialize

---

RELEASE.md

Update changelog with release

---

gen/pb-go/bundle/v1/sigstore_bundle.pb.go
gen/pb-go/rekor/v1/sigstore_rekor.pb.go
gen/pb-python/sigstore_protobuf_specs/dev/sigstore/bundle/v1/__init__.py
gen/pb-python/sigstore_protobuf_specs/dev/sigstore/rekor/v1/__init__.py
gen/pb-typescript/src/__generated__/sigstore_bundle.ts
gen/pb-typescript/src/__generated__/sigstore_rekor.ts
protos/sigstore_bundle.proto
protos/sigstore_rekor.proto

SETs serve two purposes: The promise of inclusion, and a signed
timestamp from Rekor. We've moved towards requiring inclusion proofs,
but SETs are still needed if no TSA timestamp is provided. This doc
update clarifies that.
Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>

Update SET docs for timestamping

---

Makefile

Docker generates files and folders as root when docker is run as root, which is the default. This means that a developer needs to sudo chown the target directory when starting from scratch, or else they can't rerun make rust, which will throw a permissions error.

Let docker clean up generated folder for rust

---

.github/workflows/rust-build.yml
gen/pb-rust/src/lib.rs

The Rust codegen source contained a docstring describing potential next steps. This codeblock being 'hypothetical' broke the default `cargo test` docstring tests -- fixed with an `ignore` attribute.

pb-rust: docstring failure hotfix

---

gen/pb-python/pyproject.toml
gen/pb-ruby/lib/sigstore_protobuf_specs/version.rb
gen/pb-rust/Cargo.lock
gen/pb-rust/Cargo.toml
gen/pb-typescript/package.json

Ref https://github.com/sigstore/protobuf-specs/issues/130

Bump versions for 0.2.1 release

---

CHANGELOG.md

Ref https://github.com/sigstore/protobuf-specs/issues/130

0.2.1 changelog

---

.github/ISSUE_TEMPLATE/release-checklist.md

Update release-checklist.md template

---

.github/workflows/python-release.yml

kebab-case is now preferred by this action.

python-release: use kebab-case

---

gen/pb-python/pyproject.toml

Preps an RC release to test #157.

python: 0.2.3rc0

---

.github/workflows/python-release.yml
gen/pb-python/pyproject.toml

It's not a real RC unless you make at least one mistake.

python: 0.2.3rc1

---

CHANGELOG.md

Just playing catch-up with some of the recent PRs.

CHANGELOG: record recent changes

---

.github/workflows/typescript-publish.yml

Needed for latest version of npm

Bump node version for typescript publish

---

.github/workflows/java-build-for-release.yml

This updates the generation and upload of the provenance, which broke due to the actions/artifact-upload breaking change. We now generate a draft release first, then generate provenance and upload to the existing draft release.

Update java build workflow

---

.github/workflows/java-build-for-release.yml

Creating a release doesn't need provenance

Fix java build workflow circular dep

---

Makefile

Closes https://github.com/sigstore/protobuf-specs/issues/285
NONE
NONE

Make sure to remove generated jsonschema files when running make clean

---

gen/pb-typescript/package.json

gen: bump JS patch version

---

CHANGELOG.md

Also added the missing v0.3.2
Ref: https://github.com/sigstore/protobuf-specs/issues/451

Add changelog for v0.3.3

---

gen/pb-python/pyproject.toml
gen/pb-ruby/lib/sigstore_protobuf_specs/version.rb
gen/pb-rust/Cargo.lock
gen/pb-rust/sigstore-protobuf-specs/Cargo.toml
gen/pb-typescript/package.json

Ref: https://github.com/sigstore/protobuf-specs/issues/451

gen: bump patch versions for v0.3.3

---

gen/pb-python/pyproject.toml

Preps 0.3.5 so I can release #467.

pyproject: prep 0.3.5

---

.github/ISSUE_TEMPLATE/release-checklist.md

Update release-checklist.md for rust

---

.github/workflows/googleapis-update.yml

fix https://github.com/sigstore/protobuf-specs/actions/runs/12836646556/job/35798685980

add git config to autoSetupRemote

---

.github/workflows/generate.yml
.github/workflows/googleapis-update.yml
.github/workflows/ruby-build.yml
protoc-builder/versions.mk

- Makes the PR title consistent with dependabot style and also refers to correct variable name.
- Runs `make all` after bumping the GOOGLEAPIS_COMMIT so that all relevant changes are included in the PR for review

fix googleapi update PR title/body, and remove comments

---

.github/workflows/java-release.yml

we need `contents:read` in order for this to run

fix permissions error in java-release

---

.github/ISSUE_TEMPLATE/release-checklist.md

Update release-checklist.md to denote jsonschema deprecation

---

.github/workflows/migrate-secrets.yml

apparently i need to checkout and specify i want an access token in order for gcloud to work ok

add steps to migrate script to fix IAM error

---

.gitattributes

this helps to optimize PR review

update .gitattributes for all codegen

---

.github/workflows/googleapis-update.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/protobuf-update.yml
.github/workflows/python-release.yml
.github/workflows/ruby-release.yml
.github/workflows/rust-release.yml

minor zizmor fixes to specify permissions

---

CHANGELOG.md

Update changelog for v0.4.1

---

gen/pb-python/pyproject.toml
gen/pb-ruby/lib/sigstore_protobuf_specs/version.rb
gen/pb-rust/Cargo.lock
gen/pb-rust/sigstore-protobuf-specs/Cargo.toml
gen/pb-typescript/package.json

Bump package versions to v0.4.1

---

CHANGELOG.md
gen/pb-python/pyproject.toml
gen/pb-ruby/lib/sigstore_protobuf_specs/version.rb
gen/pb-rust/Cargo.lock
gen/pb-rust/sigstore-protobuf-specs/Cargo.toml
gen/pb-typescript/package.json

Ref: https://github.com/sigstore/protobuf-specs/issues/638

Add CHANGELOG, bump releases for v0.4.2

---

java/README.md

update to java release flows which are more automated now
none
none

Update README.md for java releases

---

.github/workflows/container-release.yml

changes the container tag `release/service-builder/vX.Y.Z` -> `X.Y.Z`

Fix the tag on service-builder container

---

.github/workflows/python-build.yml

as per https://devguide.python.org/versions/

workflows: Update python versions to currently supported

---

CHANGELOG.md
gen/pb-python/pyproject.toml
gen/pb-ruby/lib/sigstore_protobuf_specs/version.rb
gen/pb-rust/Cargo.lock
gen/pb-rust/sigstore-protobuf-specs/Cargo.toml
gen/pb-typescript/package.json

v0.4.3 release
