sigstore/protobuf-specs

.github/workflows/java-build-for-release.yml
.github/workflows/java-build.yml
java/README.md
java/build.gradle.kts
java/gradle.properties

Triggers release builds (not releases to maven central) of java artifacts when a new tag with format `release/java/v1.2.3` is created. A corresponding github release is generated with jar artifacts AND slsa attestation. ex: https://github.com/loosebazooka/protobuf-specs/releases/tag/untagged-019d132496fa307dce96
TODO: follow up with script to release these artifacts to maven central.
fyi: @woodruffw @znewman01

Add release build for java

---

java/scripts/sign_and_bundle_release.sh

Signed-off-by: Appu Goundan <appu@google.com>
turns out this is unnecessary when uploading bundles to maven central as they are generated on the server side, so if you upload a hash, it generates hashes for that hash. hash explosion.

remove checksum generation in java bundle

---

gen/pb-python/pyproject.toml

This is just to push another alpha out the door for testing; one of the maintainers will need to tag `release/python/0.0.1a2` after this is merged.
Signed-off-by: William Woodruff <william@trailofbits.com>

pb-python: 0.0.1a2

---

gen/pb-go/rekor/v1/sigstore_rekor.pb.go
gen/pb-python/sigstore_protobuf_specs/dev/sigstore/rekor/v1/__init__.py
protos/sigstore_rekor.proto

Closes #62.
Let me know if this is too verbose 😅 
Signed-off-by: William Woodruff <william@trailofbits.com>

protos: disambiguate `canonicalized_body`

---

.github/workflows/typescript-publish.yml

Fix missing GitHub Actions permissions in typescript publishing workflow.

add missing perms to typescript-publish workflow

---

gen/pb-go/common/v1/sigstore_common.pb.go
gen/pb-python/sigstore_protobuf_specs/dev/sigstore/common/v1/__init__.py
gen/pb-typescript/src/__generated__/sigstore_common.ts
protos/sigstore_common.proto

The comment said the DER encoding, which is not what RFC6962 specifies.
We noted in root-signing that trusted_root.json's key IDs were over the DER encoding of the key, rather than the SubjectPublicKeyInfo structure, which is the raw key and an OID.

Clarify key ID is a digest over SPKI

---

gen/pb-go/dsse/envelope.pb.go
gen/pb-python/sigstore_protobuf_specs/io/intoto/__init__.py
gen/pb-typescript/src/__generated__/envelope.ts
protos/envelope.proto

This just renames `body` in the DSSE envelope docs to reflect the actual field name, which is `payload`.
CC @znewman01 @kommendorkapten

gen, protos: tweak envelope docs

---

gen/pb-go/trustroot/v1/sigstore_trustroot.pb.go
gen/pb-python/sigstore_protobuf_specs/dev/sigstore/trustroot/v1/__init__.py
gen/pb-typescript/src/__generated__/sigstore_trustroot.ts
protos/sigstore_trustroot.proto

The semantics around valid_for was not properly explained and could lead to confusion.
N/A
N/A

Clarified the intent of the listed instances in the trusted_root

---

.github/workflows/rust-release.yml
gen/pb-rust/Cargo.toml

Follows #83: this adds a release workflow for the Rust package.
~~Needs administrative action: I can create a `crates.io` token for this, but I'll need a repo owner to add it as a secret.~~

workflows: add rust-release

---

Makefile
gen/pb-go/rekor/v1/sigstore_rekor.pb.go
gen/pb-python/sigstore_protobuf_specs/dev/sigstore/rekor/v1/__init__.py
gen/pb-typescript/src/__generated__/sigstore_rekor.ts
protos/sigstore_rekor.proto

Fixed a spelling error in a comment.
Added a new `make(1)` target `docker-image-no-cache` which rebuilds the builder without layer cache.
N/A
N/A

Fixed minor spelling errors in a comment.

---

.github/dependabot.yml
Dockerfile
Makefile
gen/pb-go/bundle/v1/sigstore_bundle.pb.go
gen/pb-go/common/v1/sigstore_common.pb.go
gen/pb-go/dsse/envelope.pb.go
gen/pb-go/verification/v1/sigstore_verification.pb.go
gen/pb-typescript/src/__generated__/envelope.ts
gen/pb-typescript/src/__generated__/google/api/field_behavior.ts
gen/pb-typescript/src/__generated__/google/protobuf/descriptor.ts
gen/pb-typescript/src/__generated__/sigstore_common.ts
gen/pb-typescript/src/__generated__/sigstore_rekor.ts
gen/pb-typescript/src/__generated__/sigstore_verification.ts

I was running into an error with the Docker container updating its apt cache, updating to the latest protoc image fixed it.
Also added dependabot to keep it up to date.

Update protoc, add dependabot

---

gen/pb-go/rekor/v1/sigstore_rekor.pb.go
gen/pb-python/sigstore_protobuf_specs/dev/sigstore/rekor/v1/__init__.py
gen/pb-typescript/src/__generated__/sigstore_rekor.ts
protos/sigstore_rekor.proto

Differentiating the comments for log_index in TransparencyLogEntry versus in InclusionProof.

Clarify log index in transparency log entry vs inclusion proof

---

gen/jsonschema/schemas/CertificateAuthority.schema.json
gen/jsonschema/schemas/Input.schema.json
gen/jsonschema/schemas/TrustedRoot.schema.json
gen/pb-go/trustroot/v1/sigstore_trustroot.pb.go
gen/pb-python/sigstore_protobuf_specs/dev/sigstore/trustroot/v1/__init__.py
gen/pb-rust/schemas/CertificateAuthority.schema.json
gen/pb-rust/schemas/Input.schema.json
gen/pb-rust/schemas/TrustedRoot.schema.json
gen/pb-typescript/src/__generated__/sigstore_trustroot.ts
protos/sigstore_trustroot.proto

Closes https://github.com/sigstore/protobuf-specs/issues/132
Clarified the intent of the uri field in the certificate authority
Clarified the `uri` field of the certificate authority message in the trust root.
N/A

Clarified the intent of the uri field in the certificate authority

---

gen/jsonschema/schemas/Bundle.schema.json
gen/jsonschema/schemas/Input.schema.json
gen/pb-go/bundle/v1/sigstore_bundle.pb.go
gen/pb-python/sigstore_protobuf_specs/dev/sigstore/bundle/v1/__init__.py
gen/pb-rust/schemas/Bundle.schema.json
gen/pb-rust/schemas/Input.schema.json
gen/pb-typescript/src/__generated__/sigstore_bundle.ts
protos/sigstore_bundle.proto

Clarified how the use of (reduntant) key hint.
Key hint is both specified in the bundle's `verification material` but may also be specified inside the `content` if it'a DSSE envelope. This discussion started in this PR https://github.com/sigstore/protobuf-specs/pull/145
This PR favours simplicity over efficiency; that is; the key hint should be equal and duplicated to simplify any consumption of the bundle, as the value may appear in multiple places. The key hint (if used) is usually a short string so I argue it's not too bad.
Clarified how to populate the key hint in the bundle, when the content is a DSSE envelope with a key hint too.
This PR is only documentation.

Clarify key hint

---

.github/workflows/python-build.yml
gen/pb-python/pyproject.toml

This drops Python 3.7, since sigstore-python doesn't support it.
It adds Python 3.12 to the test matrix and bumps `betterproto` in the process, since the `b6` release avoids the deprecated `pkg_resources` module; see https://github.com/sigstore/sigstore-python/pull/801.

python: support 3.12, drop 3.7, bump betterproto

---

gen/pb-python/pyproject.toml

Gets #151 out the door. Once merged, I'll cut the appropriate release tag as well.

python: prep 0.2.2 release

---

.github/workflows/python-release.yml

I've configured the corresponding publisher on the PyPI side, so this should work out of the box.
Now that we're using trusted publishing, the `PYPI_TOKEN` secret can be safely removed. Separately, I'll remove the token on the PyPI side as well.
Closes #154.

python-release: use trusted publishing

---

gen/jsonschema/schemas/Bundle.schema.json
gen/jsonschema/schemas/Input.schema.json
gen/jsonschema/schemas/VerificationMaterial.schema.json
gen/pb-go/bundle/v1/sigstore_bundle.pb.go
gen/pb-python/sigstore_protobuf_specs/dev/sigstore/bundle/v1/__init__.py
gen/pb-python/sigstore_protobuf_specs/dev/sigstore/verification/v1/__init__.py
gen/pb-rust/schemas/Bundle.schema.json
gen/pb-rust/schemas/Input.schema.json
gen/pb-rust/schemas/VerificationMaterial.schema.json
gen/pb-typescript/src/__generated__/sigstore_bundle.ts
protos/sigstore_bundle.proto

Addresses https://github.com/sigstore/sig-clients/issues/9
This PR adds a definition for Sigstore's DSSE signature extension. The definition is a subset of the current VerificationMaterials message, omitting the option for a key ID in place of the cert chain. This is because the sigstore signature extension in a DSSE signature must only be used to communicate the intermediate certs and timestamp / tlog info.
https://github.com/secure-systems-lab/dsse/pull/61 introduces extensions to the DSSE specification.
Define DSSE signature extension for Sigstore signatures.
None.

Add definition for Sigstore's DSSE signature extension

---

CHANGELOG.md
gen/pb-python/pyproject.toml
gen/pb-ruby/lib/sigstore_protobuf_specs/version.rb
gen/pb-rust/Cargo.lock
gen/pb-rust/Cargo.toml
gen/pb-typescript/package.json

v0.3.0 release
See updated CHANGLOG
Rendered [CHANGELOG](https://github.com/kommendorkapten/protobuf-specs/blob/changelog-v3-b3/CHANGELOG.md)

Prepare for a v0.3.0 release

---

gen/pb-rust/Cargo.lock
gen/pb-rust/sigstore-protobuf-specs-derive/Cargo.toml
gen/pb-rust/sigstore-protobuf-specs/Cargo.toml

Preps a patch for the failed 0.3.0 release.

Rust 0.3.1

---

.github/workflows/typescript-build.yml
gen/pb-typescript/package-lock.json
gen/pb-typescript/package.json
gen/pb-typescript/tsconfig.json

Updates the typescript package to specify node16 as the oldest supported runtime (node14 is far out of support at this point).
Note: there's no need to cut a new release after merging these changes, we can wait until the next protobuf update.

target node16 for typescript package

---

gen/pb-rust/Cargo.lock
gen/pb-rust/sigstore-protobuf-specs/Cargo.toml

Now that the codegen is AOT and we have dry-run publishing in CI, there should be no more surprises. Famous last words.

rust: 0.3.3

---

.github/workflows/java-build-for-release.yml

No reason to create a draft, we move straight to generate a prerelease, and then the provenance should be attached to that existing prerelease.

Update java builder to generate prerelease

---

gen/pb-ruby/lib/sigstore_protobuf_specs.rb

By only loading the generated protobuf ruby files and not the "sigstore_protobuf_specs" file
Before:
```sh
$ chruby-exec ruby-2.7 -- ruby -w -rbundler/inline -e 'gemfile { source "https://rubygems.org"; gemspec }; require "sigstore_protobuf_specs"'
/Users/segiddins/.rubies/ruby-2.7.5/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:38: warning: /Users/segiddins/.rubies/ruby-2.7.5/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:38: warning: loading in progress, circular require considered harmful - /Users/segiddins/Development/github.com/sigstore/protobuf-specs/gen/pb-ruby/lib/sigstore_protobuf_specs.rb
from -e:1:in  `<main>'
from /Users/segiddins/.rubies/ruby-2.7.5/lib/ruby/site_ruby/2.7.0/bundler/inline.rb:42:in  `gemfile'
from …
```

Avoid circular require in generated Ruby code

---

Makefile

Local builds seem to fail with the old order (unless root)
related to #244

Update make all order

---

gen/pb-python/pyproject.toml
gen/pb-ruby/lib/sigstore_protobuf_specs/version.rb
gen/pb-rust/Cargo.lock
gen/pb-rust/sigstore-protobuf-specs/Cargo.toml
gen/pb-typescript/package.json

Rust bumped to v0.3.4 due to a few additional releases.
Ref: https://github.com/sigstore/protobuf-specs/issues/282

Bump versions for v0.3.1

---

CHANGELOG.md
gen/pb-python/pyproject.toml
gen/pb-ruby/lib/sigstore_protobuf_specs/version.rb
gen/pb-rust/Cargo.lock
gen/pb-rust/sigstore-protobuf-specs/Cargo.toml

A couple of useful changes have landed since the last patch release, so this bumps the patch versions where relevant 🙂

gen: bump patch versions

---

.github/workflows/java-release.yml
java/build.gradle.kts
java/scripts/sign_and_bundle_release.sh

This still needs a user to run the release script to sign with pgp locally and push the bundle to maven central.
SLSA generation has been removed temporarily. I'll figure out how to integrate with the github attestation generator in the future.

Update java release to do sigstore sign on github

---

gen/pb-rust/Cargo.toml

In order for the sigstore_protobuf_specs crate to
be packaged in a Fedora RPM we need the crate
to include the necessary license metadata.
Please see https://github.com/bpfman/bpfman/issues/1127 for more information.
None.
None.

add license to rust protobuf bindings

---

gen/pb-rust/Cargo.lock
gen/pb-rust/sigstore-protobuf-specs/Cargo.toml

Preps a version for #327.
(As part of this: I propose that the next round of patch releases for all clients "fast-forward" to 0.3.6 so that they're once again consistent with each other. This should be a one-time operation, since we'll use pre-releases more aggressively for build debugging in the future 😅.)

rust: bump patch

---

go.mod

PR updates the `go` directive to `go 1.21` from `go 1.18` in `go.mod` file.  Both direct dependencies contain that version in their respective go.mod files:
* https://github.com/googleapis/go-genproto/blob/796eee8c2d537a6e5c8de22908f4facea945ebde/googleapis/api/go.mod#L3
* https://github.com/protocolbuffers/protobuf-go/blob/v1.35.1/go.mod#L3

update go to 1.21 in go.mod

---

Makefile
gen/pb-python/pyproject.toml
gen/pb-python/sigstore_protobuf_specs/dev/sigstore/bundle/v1/__init__.py
gen/pb-python/sigstore_protobuf_specs/dev/sigstore/common/v1/__init__.py
gen/pb-python/sigstore_protobuf_specs/dev/sigstore/events/v1/__init__.py
gen/pb-python/sigstore_protobuf_specs/dev/sigstore/rekor/v1/__init__.py
gen/pb-python/sigstore_protobuf_specs/dev/sigstore/trustroot/v1/__init__.py
gen/pb-python/sigstore_protobuf_specs/dev/sigstore/verification/v1/__init__.py
gen/pb-python/sigstore_protobuf_specs/google/api/__init__.py
gen/pb-python/sigstore_protobuf_specs/io/intoto/__init__.py

~~WIP; this is experimental.~~
This should improve the quality/DX of the Python protobuf-specs a bit, by allowing them to be used as Pydantic dataclasses.
As a downside, this is an API breaking change for the Python bindings. However, sigstore-python strictly pins to each version so this shouldn't be a huge issue.

use Pydantic dataclasses for Python bindings

---

.github/workflows/typescript-build.yml
.github/workflows/typescript-publish.yml
gen/pb-typescript/package-lock.json
gen/pb-typescript/package.json
gen/pb-typescript/tsconfig.json

Fixes #464 
Sets the minimum node version to v18.17.x. Updates the `typescript` and `tsconfig` dependencies accordingly.

update typescript package to node18

---

Makefile
protoc-builder/Dockerfile.go
protoc-builder/Dockerfile.protoc
protoc-builder/Dockerfile.ruby
protoc-builder/Dockerfile.typescript

Fixes: #251 
This switches the base image for `protoc-base` from alpine to debian because alpine doesn't support the full range of UID/GID values that debian does. 
this allows you to `make clean && make all` without `sudo` :)

build protoc-* containers as nonroot

---

Makefile
protoc-builder/Dockerfile.go
protoc-builder/Dockerfile.protoc
protoc-builder/Dockerfile.python
protoc-builder/Dockerfile.ruby
protoc-builder/Dockerfile.rust
protoc-builder/Dockerfile.typescript
protoc-builder/versions.mk

After looking at this a bit more, we may need the ability to independently evolve the versions of `protoc` and `googleapis/googleapis` for each language we do code generation for. This updates the Makefile and Docker build processes to use a single Dockerfile and default version, with an explicit override if necessary for a specific language.
I plan on making use of this when submitting bumps of relevant configs for each language we support in this repo, but for the sake of showing that this doesn't affect the current result of the repo, this PR should not change any generated code.

allow each language to specify protoc, googleapis versions independently

---

.github/dependabot.yml

fix: dependabot typo "s/pypi/pip"

---

.github/workflows/python-build.yml
.github/workflows/ruby-build.yml
.github/workflows/rust-build.yml
.github/workflows/typescript-build.yml

ensure we get build coverage on python, rust, ruby, typescript when changes are proposed by dependabot

trigger language-specific builds on protoc-builder changes

---

README.md

Per discussion in #477 we are formally deprecating the jsonschema files in this repository.
Fixes: #477

add deprecation notice for jsonschema

---

.github/workflows/gradle-wrapper-validation.yml
.github/workflows/java-build.yml
.github/workflows/java-release.yml
.github/workflows/python-build.yml
.github/workflows/python-release.yml
.github/workflows/ruby-build.yml
.github/workflows/ruby-release.yml
.github/workflows/rust-build.yml
.github/workflows/rust-release.yml
.github/workflows/typescript-build.yml
.github/workflows/typescript-publish.yml
java/README.md

This fixes issues reported by zizmor 🌈, as well as removing a dependency on a third-party action when the `gh` CLI should work just fine.
This also moves the gradle wrapper validation check to a non-deprecated action.
@loosebazooka @woodruffw fyi

address zizmor issues, remove 3p action for creating release for java

---

.github/workflows/migrate-secrets.yml

this should be a one time script to read our publish tokens out of GitHub Actions secrets and copy them into GCP secret manager
once this is run successfully, I'll update the release flows to read from secret manager and delete the secrets from the repo
this gives oncall more explicit control of our tokens and an audit log

script to move publish tokens to GCP secret manager

---

.github/workflows/ruby-release.yml
.github/workflows/rust-release.yml

Need to explicitly declare id-token:write for WLI.

Fix Ruby and Rust release workflows

---

.github/workflows/generate.yml

without this we're running the code gen test twice on dependabot PRs because its a push to a local branch AND a PR.

don't run the code gen test twice on PRs

---

gen/pb-typescript/package-lock.json
gen/pb-typescript/package.json
gen/pb-typescript/src/rekor/v2/index.ts

Updates the generated `@sigstore/protobuf-specs` npm package to export the Rekor v2 types added in #661.

export rekor types from pb-typescript

---

RELEASE.md

Updates the TypeScript release instructions to include a step to regenerate the `package-lock.json` file. This will ensure that the version in `package-lock.json` file matches the `package.json`.

update release instructions for typescript
